{
 "title": "Navien",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }, "options": { "content": "# Navien" } },
  {
   "title": "Controller Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Controller Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "controller_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Panel Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "panel_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operating Time (hrs)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Operating Time (hrs)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "total_operating_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas - Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Inlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "inlet_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "outlet_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Set Point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "set_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$D * $C", "type": "math" }
   ]
  },
  {
   "title": "Accumulated Gas Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Gas Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "accumulated_gas_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Domestic Consumption Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "On/Off Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "accumulated_domestic_usage_cnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water - Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "alias": "Inlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "inlet_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outlet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "outlet_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Set Point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "set_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "flow_lpm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kcal" } },
   "targets": [
    {
     "alias": "Gas usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "select": [
      [
       { "params": [ "current_gas_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water tap is on",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Consumption Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "consumption_active" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Operating Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "operating_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commands sent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expression": "$A && $B", "type": "math" },
    { "expression": "$A && (!$B)", "type": "math" },
    { "expression": "$E && $F", "type": "math" },
    { "expression": "$E && (!$F)", "type": "math" },
    { "expression": "$C && $G", "type": "math" },
    {
     "alias": "NaviLink Ack",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "announce",
     "select": [
      [
       { "params": [ "navilink_present" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Power",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "system_power" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Schedule Active",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 26 },
   "targets": [
    {
     "alias": "Schedule",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "schedule_active" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NaviLink Present",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 26 },
   "targets": [
    {
     "alias": "Schedule",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "announce",
     "select": [
      [
       { "params": [ "navilink_present" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recirculation Active/Running",
   "type": "heywesty-trafficlight-panel",
   "description": "If recirculation is active, but not running, it will show yellow. If it is running, it shows green.",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 26 },
   "targets": [
    { "expression": "$C * 0.5 + $C * $A * 0.5", "type": "math" }
   ]
  },
  {
   "title": "Hot Button Running",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 26 },
   "targets": [
    {
     "alias": "Recirculation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "hotbutton_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}